services:
  mt5linux:
    image: lprett/mt5linux:latest
    container_name: mt5linux
    environment:
      MT5_HOST: ${MT5_HOST:-0.0.0.0}
      VNC_PASSWORD: ${VNC_PASSWORD:-password}
    ports:
      - ${NVC_PORT:-6081}:6081
      - ${MT5_PORT:-18812}:18812
    restart: "no"
    stdin_open: true
    tty: true
